    AREA PROG, CODE, READONLY
ZEROS RN R0;
ONES RN R1;
    LDR R2,=MEMORY
    LDRH R3, [R2]
    MOV R5, #1
AGAIN
    AND R4, R3, R5
    CMP R4, #0
    BNE INC_1
    ADD ZEROS, #1
    B SKIP
INC_1
    ADD ONES, #1
SKIP
    LSL R5, #1
    CMP R5, #0x10000
    BNE AGAIN
STOP B STOP
MEMORY DCB 0x45, 0x0F
    ALIGN
    END